server.port=${SERVER_PORT:8081}
server.servlet.context-path=/eloryks/api/v1

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/eloryks-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:eloryks-app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:batman}

spring.jpa.properties.hibernate.default_schema=eloryks
spring.jpa.open-in-view=false

springdoc.swagger-ui.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

storage.account.name=${STORAGE_ACCOUNT_NAME:}
storage.account.key=${STORAGE_ACCOUNT_KEY:}
storage.protected.container=${STORAGE_PROTECTED_CONTAINER:protected}

servicebus.connection-string=${SERVICEBUS_CONNECTION_STRING:}
servicebus.namespace=${SERVICEBUS_NAMESPACE:}
servicebus.queue=${SERVICEBUS_QUEUE:telemetry-queue}
